# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true

# Sidebar
widgets:
- search
- music
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:xixi
duoshuo_shortname: xixi
rss: xixi
google_site_verification: xixi
baidu_site_verification: 
favicon: xixi
music: xixi